import "./globals.css";
import { Ubuntu } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import NoHeader from "./NoHeader";

const UbuntuSans = Ubuntu({
  variable: "--font-ubuntu-sans",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${UbuntuSans.variable}  h-full antialiased`}
    >
      <body>
        <NoHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
